UvFifo class updates for tcp client
grumpycoders/pcsx-redux pull request #840
Opened 2022-05-16 06:14 UTC by caldog20

2022-05-17 01:42 UTC, nicolasnoble requested changes

2022-05-17 01:42 UTC, nicolasnoble commented on src/support/uvfile.h
> +    void process(uv_tcp_t*);
Maybe rename this to `startRead` ?

2022-05-17 01:56 UTC, caldog20 commented on src/support/uvfile.cc
> +                free(fifo->m_buffer);
This needs a return on the outer if statement I believe.

2022-05-18 03:04 UTC, nicolasnoble commented on src/support/uvfile.cc
> +                                        return;
You still need a `fifo->m_failed.test_and_set()` here :)

2022-05-18 03:19 UTC, merged