Add a context menu to editable registers, move PC under GPR
grumpycoders/pcsx-redux pull request #885
Opened 2022-06-14 22:54 UTC by xyzz

Several things here that I personally find useful during reverse engineering

![image](https://user-images.githubusercontent.com/1065521/173702224-32d5bf18-06f8-4382-b683-247e93d389dc.png)

Also move PC under GPR so you don't have switch tabs to access it (it's currently the only other editable register not under GPR).

2022-06-19 18:15 UTC, nicolasnoble requested changes

2022-06-19 18:15 UTC, nicolasnoble commented on src/gui/widgets/registers.cc
> -            ImGui::Text("pc   : %08x", registers->pc);
I wouldn't remove it completely.

2022-06-19 18:15 UTC, nicolasnoble commented on src/gui/widgets/registers.cc
> +            std::vector<std::pair<const char*, uint32_t>> regs;
Let's avoid this pattern - it'll be run on every refresh still... instead let's just add a `ImGui::Separator()` at the end of the loop and add `pc` there in a special manner. We should also probably just factor all the "show a register" code into a separate function to be able to reuse it on any register, not just the GPRs.

2022-06-30 23:10 UTC, xyzz commented
Added separator to PC under GPR, and another copy is also editable under Misc

![image](https://user-images.githubusercontent.com/1065521/176793252-5edeeef1-0b10-40b5-b20e-20acc691e7f4.png)

![image](https://user-images.githubusercontent.com/1065521/176793178-7da52df6-cd89-4b12-a180-f004dbcbf563.png)

2022-07-02 00:09 UTC, nicolasnoble approved these changes
Awesome, thanks :)

2022-07-02 00:09 UTC, merged